version: '3'

services:
  server:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ${STATIC_PATH}:/code
      - ${FIU_PATH}:/code/fiu
      - ${TESTS_PATH}:/code/tests
      - ${BAZA_PATH}:/code/baza
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
